
server:
  port: 10444
  context-path: /kt/drills/api
#  ssl:
#    key-store:
#    key-password:
#    key-store-type:
#    key-alias:

spring:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none

com:
  virohtus:
    keeperteacher:
      drills:
